"""empty message

Revision ID: 44e96c3d20aa
Revises: 93a585693206
Create Date: 2026-03-12 12:34:14.986945

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "44e96c3d20aa"
down_revision: Union[str, Sequence[str], None] = "93a585693206"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
