"""empty message

Revision ID: 5eb2d13de4cd
Revises: d8e97ac6be87
Create Date: 2026-03-10 16:58:17.942516

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5eb2d13de4cd"
down_revision: Union[str, Sequence[str], None] = "d8e97ac6be87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("seller_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_category_id"), "products", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_products_seller_id"), "products", ["seller_id"], unique=False
    )
    op.drop_index(op.f("ix_ products_category_id"), table_name=" products")
    op.drop_index(op.f("ix_ products_seller_id"), table_name=" products")
    op.drop_table(" products")
    # ### end Alembic commands ###


productstatus_enum = postgresql.ENUM(
    "DRAFT",
    "PENDING",
    "PUBLISHED",
    "REJECTED",
    name="productstatus",
    create_type=False,
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        " products",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("seller_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("status", productstatus_enum, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updatet_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f(" products_category_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["users.id"], name=op.f(" products_seller_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f(" products_pkey")),
    )
    op.create_index(
        op.f("ix_ products_seller_id"), " products", ["seller_id"], unique=False
    )
    op.create_index(
        op.f("ix_ products_category_id"), " products", ["category_id"], unique=False
    )
    op.drop_index(op.f("ix_products_seller_id"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
