"""empty message

Revision ID: 93a585693206
Revises: eb81cf45605a
Create Date: 2026-03-11 18:48:58.853017

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "93a585693206"
down_revision: Union[str, Sequence[str], None] = "eb81cf45605a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
