"""empty message

Revision ID: d8e97ac6be87
Revises: e804829c8eae
Create Date: 2026-03-10 12:38:09.736622

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8e97ac6be87"
down_revision: Union[str, Sequence[str], None] = "e804829c8eae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    role_table = sa.table(
        "roles",
        sa.column("name", sa.String),
    )

    op.bulk_insert(
        role_table,
        [
            {"name": "buyer"},
            {"name": "seller"},
            {"name": "admin"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
