"""empty message

Revision ID: eb81cf45605a
Revises: 5eb2d13de4cd
Create Date: 2026-03-11 16:02:41.937602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb81cf45605a"
down_revision: Union[str, Sequence[str], None] = "5eb2d13de4cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("published", sa.Boolean(), nullable=False))
    op.drop_column("products", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_column("products", "published")
    # ### end Alembic commands ###
